name: portfolio
channels:
  - defaults
dependencies:
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.8.13
  - setuptools=65.5.0
  - sqlite=3.39.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - beautifulsoup4==4.11.1
    - charset-normalizer==2.1.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - fonttools==4.38.0
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.1
    - numpy==1.23.4
    - packaging==21.3
    - pillow==9.3.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - requests==2.28.1
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - urllib3==1.26.12
